name: Build dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build dylib
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: MinhDuc-dylib
          path: libMinhDuc.dylib
